### ISSUE TITLE
Error when running `website-change.sh` test

### ISSUE THREAD

**Issue by HarimbolaSantatra** [HarimbolaSantatra/mm-cli#36]
## Reproduce

    ./test/website-change.sh

## Result
```
./test/website-change.sh
Traceback (most recent call last):
  File "/home/santatra/projet_kely/mm-cli/./mm-scraping", line 134, in <module>
    main()
  File "/home/santatra/projet_kely/mm-cli/./mm-scraping", line 130, in main
    print(doc.print_table())
  File "/home/santatra/projet_kely/mm-cli/./mm-scraping", line 118, in print_table
    return json.dumps(self.get_result_pairs())
  File "/home/santatra/projet_kely/mm-cli/./mm-scraping", line 105, in get_result_pairs
    table.next_sibling.next_sibling.find("span", class_="minute").extract()
AttributeError: 'NoneType' object has no attribute 'extract'
make: *** [Makefile:26: test] Error 123
```

**Comment by HarimbolaSantatra** [comment]
Fixed by 44e7f06db8769fd44653b02577c19f484a11bc55
